pipelines:
  mypipe:
    materials:
      git: https://github.com/LaurasJ/testweb.git
    stages:
      - laurosrepisyaml:
        jobs:
          laurojobisyaml:
            tasks:
              - exec:
                command: ./test.sh
                working_directory: testweb/scripts
