resources:
- name : myrepo
  type : git
  source:
    uri : https://github.com/LaurasJ/testweb.git
    branch : master

jobs:
- name : printout
  plan:
  - get : myrepo
  - task: say-hello
    config:
      platform : linux
      image_resource:
        type: docker-image
        source: {repository: ubuntu}
      run:
        path: ls
        args: [-las]
  - task : print
    file : myrepo/scripts/test.yml
