resources:
- name : myrepo
  type : git
  source:
    uri : https://github.com/LaurasJ/testweb.git
    branch : master

jobs:
- name : printout
  plan:
  - get : myrepo
  - task : print
    file : scripts/test.yml
